export type Plant = {
  id: string;
  name: string;
  price: number;
  image: string;
  description: string;
  careLevel: 'Easy' | 'Moderate' | 'Difficult';
  lighting: 'Low' | 'Medium' | 'Bright';
};

export const plants: Plant[] = [
  {
    id: '1',
    name: 'Monstera Deliciosa',
    price: 149,
    image: 'https://placehold.co/600x600.png',
    description: 'Iconic split leaves, adds a tropical touch. A relatively easy-to-care-for statement plant.',
    careLevel: 'Easy',
    lighting: 'Bright',
  },
  {
    id: '2',
    name: 'Snake Plant',
    price: 99,
    image: 'https://placehold.co/600x600.png',
    description: 'Hardy and architectural, thrives on neglect and purifies the air. Perfect for beginners.',
    careLevel: 'Easy',
    lighting: 'Low',
  },
  {
    id: '3',
    name: 'Fiddle Leaf Fig',
    price: 149,
    image: 'https://placehold.co/600x600.png',
    description: 'A design favorite with large, violin-shaped leaves. Rewards consistent care with stunning growth.',
    careLevel: 'Difficult',
    lighting: 'Bright',
  },
  {
    id: '4',
    name: 'ZZ Plant',
    price: 119,
    image: 'https://placehold.co/600x600.png',
    description: 'Drought-tolerant gem with glossy, dark green leaves. Handles low light and infrequent watering.',
    careLevel: 'Easy',
    lighting: 'Low',
  },
  {
    id: '5',
    name: 'Pothos',
    price: 79,
    image: 'https://placehold.co/600x600.png',
    description: 'Incredibly resilient vining plant. Great for hanging baskets or trailing down shelves.',
    careLevel: 'Easy',
    lighting: 'Medium',
  },
  {
    id: '6',
    name: 'Calathea Orbifolia',
    price: 139,
    image: 'https://placehold.co/600x600.png',
    description: 'Famous for its large, round leaves with beautiful silver stripes. Loves humidity.',
    careLevel: 'Moderate',
    lighting: 'Medium',
  },
  {
    id: '7',
    name: 'Bird of Paradise',
    price: 149,
    image: 'https://placehold.co/600x600.png',
    description: 'Bring a dramatic, tropical flair indoors with its large, banana-like leaves.',
    careLevel: 'Moderate',
    lighting: 'Bright',
  },
  {
    id: '8',
    name: 'Spider Plant',
    price: 89,
    image: 'https://placehold.co/600x600.png',
    description: 'A classic and charismatic houseplant with arching leaves. Easy to propagate.',
    careLevel: 'Easy',
    lighting: 'Bright',
  },
  {
    id: '9',
    name: 'Aloe Vera',
    price: 69,
    image: 'https://placehold.co/600x600.png',
    description: 'A succulent known for its medicinal properties. Easy to care for and requires bright light.',
    careLevel: 'Easy',
    lighting: 'Bright',
  },
  {
    id: '10',
    name: 'Peace Lily',
    price: 109,
    image: 'https://placehold.co/600x600.png',
    description: 'Elegant plant with dark green leaves and white flowers. Known for its air-purifying qualities.',
    careLevel: 'Easy',
    lighting: 'Medium',
  },
  {
    id: '11',
    name: 'Jade Plant',
    price: 85,
    image: 'https://placehold.co/600x600.png',
    description: 'A popular good luck succulent with thick, woody stems and glossy green leaves.',
    careLevel: 'Easy',
    lighting: 'Bright',
  },
  {
    id: '12',
    name: 'Rubber Plant',
    price: 129,
    image: 'https://placehold.co/600x600.png',
    description: 'Features large, dark, glossy leaves. A low-maintenance plant that can grow into a small tree.',
    careLevel: 'Easy',
    lighting: 'Medium',
  },
  {
    id: '13',
    name: 'String of Pearls',
    price: 95,
    image: 'https://placehold.co/600x600.png',
    description: 'A unique trailing succulent with pea-shaped leaves. Perfect for hanging planters.',
    careLevel: 'Moderate',
    lighting: 'Bright',
  },
  {
    id: '14',
    name: 'Prayer Plant',
    price: 115,
    image: 'https://placehold.co/600x600.png',
    description: 'Known for leaves that fold up at night. Features striking patterns on its foliage.',
    careLevel: 'Moderate',
    lighting: 'Medium',
  },
  {
    id: '15',
    name: 'Chinese Money Plant',
    price: 99,
    image: 'https://placehold.co/600x600.png',
    description: 'Also known as Pilea, it has unique, coin-shaped leaves and is easy to propagate.',
    careLevel: 'Easy',
    lighting: 'Bright',
  },
  {
    id: '16',
    name: 'Anthurium',
    price: 135,
    image: 'https://placehold.co/600x600.png',
    description: 'Features bright, heart-shaped flowers and glossy green leaves, adding a splash of color.',
    careLevel: 'Moderate',
    lighting: 'Medium',
  },
  {
    id: '17',
    name: 'Boston Fern',
    price: 90,
    image: 'https://placehold.co/600x600.png',
    description: 'A classic fern with lush, feathery fronds. Thrives in humid environments.',
    careLevel: 'Moderate',
    lighting: 'Medium',
  },
  {
    id: '18',
    name: 'Orchid',
    price: 145,
    image: 'https://placehold.co/600x600.png',
    description: 'Elegant and exotic, orchids have beautiful, long-lasting blooms. Requires specific care.',
    careLevel: 'Difficult',
    lighting: 'Bright',
  },
  {
    id: '19',
    name: 'Air Plant (Tillandsia)',
    price: 59,
    image: 'https://placehold.co/600x600.png',
    description: 'Doesn\'t require soil and can be mounted on various surfaces. Needs regular misting.',
    careLevel: 'Easy',
    lighting: 'Bright',
  },
  {
    id: '20',
    name: 'Croton',
    price: 125,
    image: 'https://placehold.co/600x600.png',
    description: 'Known for its vibrant, multi-colored foliage. Adds a bold statement to any space.',
    careLevel: 'Moderate',
    lighting: 'Bright',
  }
];
